name: PetApp CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:

    # 1️⃣ Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2️⃣ Setup Java (FIXED)
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️⃣ Build Application (SKIP Integration Tests)
    - name: Build with Maven
      run: mvn clean install -DskipITs

    # 4️⃣ Run Unit Tests
    - name: Run Unit Tests
      run: mvn test

    # 5️⃣ SonarCloud Scan (FIXED 🔥)
    - name: SonarCloud Scan
      run: |
        mvn clean package -DskipTests sonar:sonar \
        -Dsonar.projectKey=snehalshirsath03_petclinic \
        -Dsonar.organization=snehalshirsath03 \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # 6️⃣ Build Docker Image
    - name: Build Docker Image
      run: docker build -t petapp .

    # 7️⃣ Login to Nexus Docker Registry
    - name: Login to Nexus
      run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

    # 8️⃣ Tag Docker Image
    - name: Tag Image
      run: docker tag petapp ${{ secrets.NEXUS_URL }}/petapp:latest

    # 9️⃣ Push to Nexus
    - name: Push to Nexus
      run: docker push ${{ secrets.NEXUS_URL }}/petapp:latest
